In [1]:

import numpy as np

In [10]:
a = np.array([(3 , 5) , (9 , 8) ])
b = np.array([(8 , 7) , ( 8 ,6)])

print(a , end = " = a\n\n")
print(b , end = " = b \n\n")

[[3 5]
 [9 8]] = a

[[8 7]
 [8 6]] = b 



In [11]:
#ADdition
print(a+b)

[[11 12]
 [17 14]]


In [12]:
#Sub
print(a - b)

[[-5 -2]
 [ 1  2]]


In [13]:
#Scalar Multiplication

print(2*a)

[[ 6 10]
 [18 16]]


In [14]:
#Transpose
print(a.T)

[[3 9]
 [5 8]]


In [15]:
a = np.array([(1 , 2) , (3 , 4) ])
b = np.array([(2 , 1) , ( 0 ,2)])

print(a)
print(b)

print("\n\n")
#Matrix Multiplication
print(a*b)

[[1 2]
 [3 4]]
[[2 1]
 [0 2]]



[[2 2]
 [0 8]]


In [16]:
#dot product

u = np.array([3,5])
v = np.array([2,7])

#print(u*v)
np.dot(a , b)

array([[ 2,  5],
       [ 6, 11]])

In [18]:
#Inverse of Matrix

a = np.array([(3 , 5) , (9 , 8)])
ainv = np.linalg.inv(a)
#print(e)

In [19]:
print(np.dot(a,ainv))

[[1. 0.]
 [0. 1.]]


In [ ]:
print("Daman",end =" ergfves")
print("Deep")

In [4]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]

#HW: WIthout using any library , add two matrix, mul two matrix

1
3
